### ISSUE TITLE
Add metadata

### ISSUE THREAD

**Issue by Aariq** [EcosystemEcologyLab/fluxtower-sites#4]
There should be a metadata.md file in `data/` describing the files in that directory:

- where is the data from
- who compiled it
- what the column names mean
- what units each column is in.

I'm also not 100% sure which of these CSVs is needed.

**Comment by lbell3141** [comment]
I wrote up a readme but can't push to the data folder due to restricted access. Are you able to resolve that or does Dr. Moore need to give me access? 

In terms of the readme itself, I'm not sure of the specifics for the fluxnet metadata files, so Dr. Moore may need to fill in some gaps in knowledge there (e.g. where exactly the data was downloaded from the FluxNet website).

I'm not sure what the exact end goal of this specific repo is, so the two fluxnet metadata files may be important for something else, but in terms of calculating footprints, ffp_inputs.csv is the only data file you should need. (Also note ffp_inputs is just a revised version of zm_dataset, so zm_dataset in now unnecessary).

**Comment by Aariq** [comment]
I just gave you maintainer permissions so you should be able to push or make a pull request now.  

And yeah, sorry about not having started a readme.  I'm thinking this will eventually house the flux towers dataset (with location and all the variables needed to calculate footprint radius) and the code to extract data from all the minimally processed AGB data products for each site. Alternatively, I could move this code over to https://github.com/EcosystemEcologyLab/FLUXNETMetadata if you feel like that's more appropriate.

Thanks for the clarification on the datasets!

**Comment by lbell3141** [comment]
Thank you for updating that! I just uploaded the simple metadata file I wrote up last week. 

I think it makes sense to keep the two repos separate. Let me know if that means the footprint function and code I used to make the ffp_inputs.csv should be cleaned up and copied over to this repo.
